# Generated by Django 4.1.4 on 2022-12-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ManyToManyField(to='service.serviceprovided'),
        ),
    ]
