# Generated by Django 4.1.4 on 2022-12-15 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_owner'),
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovided',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicecategory'),
        ),
    ]
