# Generated by Django 4.1.4 on 2022-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_service_created_at_remove_service_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovided',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
